export const MedicalFields = {
  GENERAL_MEDICINE: 'general_medicine',
  INTERNAL_MEDICINE: 'internal_medicine',
  CARDIOLOGY: 'cardiology',
  ENDOCRINOLOGY: 'endocrinology',
  GASTROENTEROLOGY: 'gastroenterology',
  GERIATRICS: 'geriatrics',
  INFECTIOS_DISEASES: 'infectious_diseases',
  NEPHROLOGY: 'nephrology',
  NEUROLOGY: 'neurology',
  ONCOLOGY: 'oncology',
  PULMONOLOGY: 'pulmonology',
  RHEUMATOLOGY: 'rheumatology',
  PATHOLOGY: 'pathology',
  EMERGENCY_MEDICINE: 'emergency_medicine',
  RADIOLOGY: 'radiology',
  GYNECOLOGY: 'gynecology',
  IMMUNOLOGY: 'immunology',
};
